/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyColorPicker {
    'value': string;
  }
  interface MyColorPickerAttributes extends StencilHTMLAttributes {
    'onChange'?: (event: CustomEvent) => void;
    'value'?: string;
  }

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyColorPicker': Components.MyColorPicker;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'my-color-picker': Components.MyColorPickerAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLMyColorPickerElement extends Components.MyColorPicker, HTMLStencilElement {}
  var HTMLMyColorPickerElement: {
    prototype: HTMLMyColorPickerElement;
    new (): HTMLMyColorPickerElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'my-color-picker': HTMLMyColorPickerElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'my-color-picker': HTMLMyColorPickerElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
